name: Rest-Assured-Allure

on:
  workflow_dispatch:

  schedule:
    - cron: "0 9 * * *"

permissions:
  contents: write

jobs:
  test:
    name: Executar testes API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Executar testes
        run: mvn clean test

      - name: Instalar Allure Commandline
        run: |
          VERSION=2.34.1

          curl -L \
            -o allure.tgz \
            https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/${VERSION}/allure-commandline-${VERSION}.tgz

          tar -xzf allure.tgz

          echo "$PWD/allure-${VERSION}/bin" >> "$GITHUB_PATH"

          export PATH="$PWD/allure-${VERSION}/bin:$PATH"

          allure --version

      - name: Checkout branch allure
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: allure
          path: gh-pages

      - name: Restaurar histórico
        run: |
          if [ -d gh-pages/last-history ]; then
            echo "Restaurando histórico..."

            mkdir -p allure-results/history

            cp -r gh-pages/last-history/* allure-results/history/
          else
            echo "Nenhum histórico encontrado."
          fi

      - name: Criar executor.json
        run: |
          mkdir -p allure-results

          cat > allure-results/executor.json << EOF
          {
            "name": "GitHub Actions",
            "type": "github",
            "buildOrder": ${{ github.run_number }},
            "buildName": "Run #${{ github.run_number }}",
            "buildUrl": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "reportName": "Run #${{ github.run_number }}",
            "reportUrl": "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.run_number }}/"
          }
          EOF

      - name: Gerar relatório Allure
        run: |
          allure generate allure-results \
            --clean \
            -o allure-report

      - name: Atualizar conteúdo publicado
        run: |
          mkdir -p gh-pages

          # Guarda uma cópia desta execução
          mkdir -p gh-pages/${{ github.run_number }}
          cp -r allure-report/* gh-pages/${{ github.run_number }}/

          # Atualiza o histórico para a próxima execução
          rm -rf gh-pages/last-history
          cp -r allure-report/history gh-pages/last-history

          # Atualiza a raiz do GitHub Pages com o relatório mais recente
          cp -r allure-report/* gh-pages/

      - name: Publicar GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: allure
          publish_dir: gh-pages