name: API Tests - ServeRest

on:
  schedule:
    # Todos os dias às 09:00 UTC
    - cron: '0 9 * * *'

  workflow_dispatch:

permissions:
  contents: write
  
jobs:

  test:

    name: Executar testes API
    runs-on: ubuntu-latest


    steps:

      - name: Checkout código
        uses: actions/checkout@v4


      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'


      - name: Executar testes Rest Assured
        run: mvn clean test


      - name: Instalar Allure CLI
        if: always()
        run: |
          sudo npm install -g allure-commandline --save-dev


      - name: Verificar Allure
        if: always()
        run: |
          allure --version


      - name: Gerar relatório Allure
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_history: allure-history


      - name: Publicar relatório Allure no GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: allure
          publish_dir: allure-history